{
  "formatVersion": "1.1",
  "component": {
    "group": "com.elegaiter.sdk",
    "module": "android-record",
    "version": "0.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.elegaiter.sdk",
          "module": "android-storage",
          "version": {
            "requires": "0.2.2"
          }
        },
        {
          "group": "com.elegaiter.sdk",
          "module": "android-network",
          "version": {
            "requires": "0.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "android-record-0.2.2.aar",
          "url": "android-record-0.2.2.aar",
          "size": 25490,
          "sha512": "ff117d17e4dc6895e26da3f97cf8b847bab3dd2093c4fde9f2069634bdcec60dafa91b1d1b26e3e490243cabdaae273d68a3bcc4684f7217a4fee236326fb582",
          "sha256": "fd0158bd2c73e230b29f3b00f778ce7d08a4ab4ba353afca06482a6a8bbb41c0",
          "sha1": "18270f708e3781eadd3c81402932ab4a1d72824a",
          "md5": "d0f50b59b3bffd25066928f3b5ce4b84"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.elegaiter.sdk",
          "module": "common",
          "version": {
            "requires": "0.2.2"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.3.0"
          }
        },
        {
          "group": "com.elegaiter.sdk",
          "module": "android-storage",
          "version": {
            "requires": "0.2.2"
          }
        },
        {
          "group": "com.elegaiter.sdk",
          "module": "android-network",
          "version": {
            "requires": "0.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "android-record-0.2.2.aar",
          "url": "android-record-0.2.2.aar",
          "size": 25490,
          "sha512": "ff117d17e4dc6895e26da3f97cf8b847bab3dd2093c4fde9f2069634bdcec60dafa91b1d1b26e3e490243cabdaae273d68a3bcc4684f7217a4fee236326fb582",
          "sha256": "fd0158bd2c73e230b29f3b00f778ce7d08a4ab4ba353afca06482a6a8bbb41c0",
          "sha1": "18270f708e3781eadd3c81402932ab4a1d72824a",
          "md5": "d0f50b59b3bffd25066928f3b5ce4b84"
        }
      ]
    }
  ]
}
