{
  "formatVersion": "1.1",
  "component": {
    "group": "com.elegaiter.sdk",
    "module": "android-core",
    "version": "0.1.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "android-core-0.1.6.aar",
          "url": "android-core-0.1.6.aar",
          "size": 2077,
          "sha512": "cba4c010e502ed256fa236902c29fe3fa88cf6e38b9a06cb9cdcb4dd80beb92e15f046d5111078db6ee7f75b369da87dd31d2a5256faec4960c7e3df2455040e",
          "sha256": "9efb09c1faeaadad07ceb8908f66b4a39e53dfdcdc46c2f6b88d551d695f08d0",
          "sha1": "fba7c711e8657f4ecb7876b542246cbc319a8f1c",
          "md5": "8486c4e03f8ade5324a852e65c466432"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "android-core-0.1.6.aar",
          "url": "android-core-0.1.6.aar",
          "size": 2077,
          "sha512": "cba4c010e502ed256fa236902c29fe3fa88cf6e38b9a06cb9cdcb4dd80beb92e15f046d5111078db6ee7f75b369da87dd31d2a5256faec4960c7e3df2455040e",
          "sha256": "9efb09c1faeaadad07ceb8908f66b4a39e53dfdcdc46c2f6b88d551d695f08d0",
          "sha1": "fba7c711e8657f4ecb7876b542246cbc319a8f1c",
          "md5": "8486c4e03f8ade5324a852e65c466432"
        }
      ]
    }
  ]
}
