{
  "formatVersion": "1.1",
  "component": {
    "group": "com.elegaiter.sdk",
    "module": "common",
    "version": "0.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "common-0.2.1.aar",
          "url": "common-0.2.1.aar",
          "size": 98111,
          "sha512": "41bcdd7854c12489cef610007b9d497fd9781639e14b006468b0c0ac05e9a44cff80dc0829f13ef86135d1b3d9f71006c7feaf26e83e782f1506472726feb460",
          "sha256": "575f6fbf068e41771613094ff9da4e010004a46065d770fce817025ec9621586",
          "sha1": "169943ce448f73db0bd6a8287b42e5bd7f299f53",
          "md5": "0f736f67d6ead72a6f417673f40a88f3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "common-0.2.1.aar",
          "url": "common-0.2.1.aar",
          "size": 98111,
          "sha512": "41bcdd7854c12489cef610007b9d497fd9781639e14b006468b0c0ac05e9a44cff80dc0829f13ef86135d1b3d9f71006c7feaf26e83e782f1506472726feb460",
          "sha256": "575f6fbf068e41771613094ff9da4e010004a46065d770fce817025ec9621586",
          "sha1": "169943ce448f73db0bd6a8287b42e5bd7f299f53",
          "md5": "0f736f67d6ead72a6f417673f40a88f3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "common-0.2.1-sources.jar",
          "url": "common-0.2.1-sources.jar",
          "size": 14644,
          "sha512": "9ccafcbbd40bc81283c0c5487e70ef595587dd502ac9d12e58464ce2b3d6b687da630fad97dfe7f9607c1a0e99ee9598532786490a6d69af903e25f2d19bd9aa",
          "sha256": "61d8c2fb543c05b911e8b8f30305f2df018749cf32e5436f72c76dd4bb01e112",
          "sha1": "f4d64f377682d583ebf08079883897ee1f4e0fbf",
          "md5": "c041a9afefbbc66b2ba9673b389b8320"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "common-0.2.1-javadoc.jar",
          "url": "common-0.2.1-javadoc.jar",
          "size": 429308,
          "sha512": "8e26a60db1f2e8dd43e067316af4789bf6a8db4765bd1930d21553fb772db1d4a4185a9ac0c3da49d858da847ad8c9368bc1c6d96390059fd77aae96ffb459c5",
          "sha256": "553f6c639a8f15267782b0e8857fcede0a20a70fa6d1a024449311d54032bf4c",
          "sha1": "6a3c182e9039802d69642c8bca9b38853cd5e230",
          "md5": "bbeb2db92c5d67c2e32fb38e2291a62c"
        }
      ]
    }
  ]
}
