{
  "formatVersion": "1.1",
  "component": {
    "group": "com.elegaiter.sdk",
    "module": "android-analysis",
    "version": "0.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.elegaiter.sdk",
          "module": "android-core",
          "version": {
            "requires": "0.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "android-analysis-0.2.2.aar",
          "url": "android-analysis-0.2.2.aar",
          "size": 43885,
          "sha512": "2843c09d99d957c6cabda7cd9e7dbda3ee403cddd6221692dbd499ecb26b57f852409b688f706782f3503e96dd17e618c24a7bf2e69f656c21fbb19590f7eece",
          "sha256": "845e9375280bfd2b711d28b4a978fbac0864712ebd7a41915a5917b5123d3761",
          "sha1": "61272d72086fa97edf47f20cf0548aef0b983695",
          "md5": "a19a8888f8ae7450d3c1ebd082d98417"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.elegaiter.sdk",
          "module": "common",
          "version": {
            "requires": "0.2.2"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.elegaiter.sdk",
          "module": "android-core",
          "version": {
            "requires": "0.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "android-analysis-0.2.2.aar",
          "url": "android-analysis-0.2.2.aar",
          "size": 43885,
          "sha512": "2843c09d99d957c6cabda7cd9e7dbda3ee403cddd6221692dbd499ecb26b57f852409b688f706782f3503e96dd17e618c24a7bf2e69f656c21fbb19590f7eece",
          "sha256": "845e9375280bfd2b711d28b4a978fbac0864712ebd7a41915a5917b5123d3761",
          "sha1": "61272d72086fa97edf47f20cf0548aef0b983695",
          "md5": "a19a8888f8ae7450d3c1ebd082d98417"
        }
      ]
    }
  ]
}
