{
  "formatVersion": "1.1",
  "component": {
    "group": "com.elegaiter.sdk",
    "module": "android-analysis",
    "version": "0.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.elegaiter.sdk",
          "module": "android-core",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "android-analysis-0.2.0.aar",
          "url": "android-analysis-0.2.0.aar",
          "size": 44059,
          "sha512": "ee1acf38b5a82696147f446cbf7db89faeda703e879dde85dc4c253e56b1b9e5abfbba7277f8abebb19964a256076f7b14612811786507bbb9b712fbb941ab8b",
          "sha256": "aa4fd64d6074592d991beb850d48d3b08534c4f2308bf4fca5e186d0e1e8e588",
          "sha1": "6aeba27db4c28a171f9b0d701916c9d7051dbfca",
          "md5": "03ae535e4961d234ae9d13e0a1893698"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.elegaiter.sdk",
          "module": "common",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.elegaiter.sdk",
          "module": "android-core",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "android-analysis-0.2.0.aar",
          "url": "android-analysis-0.2.0.aar",
          "size": 44059,
          "sha512": "ee1acf38b5a82696147f446cbf7db89faeda703e879dde85dc4c253e56b1b9e5abfbba7277f8abebb19964a256076f7b14612811786507bbb9b712fbb941ab8b",
          "sha256": "aa4fd64d6074592d991beb850d48d3b08534c4f2308bf4fca5e186d0e1e8e588",
          "sha1": "6aeba27db4c28a171f9b0d701916c9d7051dbfca",
          "md5": "03ae535e4961d234ae9d13e0a1893698"
        }
      ]
    }
  ]
}
