{
  "formatVersion": "1.1",
  "component": {
    "group": "com.elegaiter.sdk",
    "module": "android-record",
    "version": "0.1.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.elegaiter.sdk",
          "module": "android-storage",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "com.elegaiter.sdk",
          "module": "android-network",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "android-record-0.1.5.aar",
          "url": "android-record-0.1.5.aar",
          "size": 13905,
          "sha512": "0910046786b96ababa51c8e35da0f9eed4ebfd0176e0c746d7c0799b0b779cb3af2942bd006721b51ed93b738a11fae42c524868bb8377c066877b1f2d34852a",
          "sha256": "e9569a78bb000f336414c06be80c23f070dedc9536543fb90112617562ecea4a",
          "sha1": "2bef3cbdec8e63d508c83d478c7898a1009314b8",
          "md5": "14bb35b5843ed4ded0e844d314ecd14c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.elegaiter.sdk",
          "module": "common",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.3.0"
          }
        },
        {
          "group": "com.elegaiter.sdk",
          "module": "android-storage",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "com.elegaiter.sdk",
          "module": "android-network",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "android-record-0.1.5.aar",
          "url": "android-record-0.1.5.aar",
          "size": 13905,
          "sha512": "0910046786b96ababa51c8e35da0f9eed4ebfd0176e0c746d7c0799b0b779cb3af2942bd006721b51ed93b738a11fae42c524868bb8377c066877b1f2d34852a",
          "sha256": "e9569a78bb000f336414c06be80c23f070dedc9536543fb90112617562ecea4a",
          "sha1": "2bef3cbdec8e63d508c83d478c7898a1009314b8",
          "md5": "14bb35b5843ed4ded0e844d314ecd14c"
        }
      ]
    }
  ]
}
