{
  "formatVersion": "1.1",
  "component": {
    "group": "com.elegaiter.sdk",
    "module": "android-storage",
    "version": "0.1.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-core",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.7.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "android-storage-0.1.9.aar",
          "url": "android-storage-0.1.9.aar",
          "size": 53202,
          "sha512": "83fe0aadbba9495037cbc4489f6c59080517ac2f901989fec6e47faadd9fe8971d7408df51b9358d19b3543e245806ea06057015952babbb4881bd61f576a2bc",
          "sha256": "8eaea9f9d2ca391d6e98230f6bb2f12830375452a39cc5f21cc5194f90e748c4",
          "sha1": "3a38e4044c4503ce435b2d8cd6cc4e5c6ae09831",
          "md5": "3d30099ade20387f0452c1b49590b2d4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.elegaiter.sdk",
          "module": "common",
          "version": {
            "requires": "0.1.9"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.security",
          "module": "security-crypto-ktx",
          "version": {
            "requires": "1.1.0-alpha06"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.7.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-core",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.7.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "android-storage-0.1.9.aar",
          "url": "android-storage-0.1.9.aar",
          "size": 53202,
          "sha512": "83fe0aadbba9495037cbc4489f6c59080517ac2f901989fec6e47faadd9fe8971d7408df51b9358d19b3543e245806ea06057015952babbb4881bd61f576a2bc",
          "sha256": "8eaea9f9d2ca391d6e98230f6bb2f12830375452a39cc5f21cc5194f90e748c4",
          "sha1": "3a38e4044c4503ce435b2d8cd6cc4e5c6ae09831",
          "md5": "3d30099ade20387f0452c1b49590b2d4"
        }
      ]
    }
  ]
}
