{
  "formatVersion": "1.1",
  "component": {
    "group": "com.elegaiter.sdk",
    "module": "android",
    "version": "0.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.elegaiter.sdk",
          "module": "common",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "com.elegaiter.sdk",
          "module": "android-ble",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "com.elegaiter.sdk",
          "module": "android-analysis",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "com.elegaiter.sdk",
          "module": "android-storage",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "com.elegaiter.sdk",
          "module": "android-network",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "com.elegaiter.sdk",
          "module": "android-user",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "com.elegaiter.sdk",
          "module": "android-record",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "com.elegaiter.sdk",
          "module": "android-core",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "android-0.1.3.aar",
          "url": "android-0.1.3.aar",
          "size": 32066,
          "sha512": "1487d4e13d147ac0dccb8dccc02d0b4424ef58d0f1eb0fe78f94633a224eae18ba905e5f5cc93e5e07537330a1846a6cf297d19e9b3b930905d8b0223512626b",
          "sha256": "7bec6346a734f4aad418a7b32e783ff3c0047ce355bab8d50328c223d6d69e42",
          "sha1": "9e1284be8e49a7c7995ab7395bfd93d84a5dd731",
          "md5": "206aa016615219d73d996ce30a62df03"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.9.3"
          }
        },
        {
          "group": "com.elegaiter.sdk",
          "module": "common",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "com.elegaiter.sdk",
          "module": "android-ble",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "com.elegaiter.sdk",
          "module": "android-analysis",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "com.elegaiter.sdk",
          "module": "android-storage",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "com.elegaiter.sdk",
          "module": "android-network",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "com.elegaiter.sdk",
          "module": "android-user",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "com.elegaiter.sdk",
          "module": "android-record",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "com.elegaiter.sdk",
          "module": "android-core",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "android-0.1.3.aar",
          "url": "android-0.1.3.aar",
          "size": 32066,
          "sha512": "1487d4e13d147ac0dccb8dccc02d0b4424ef58d0f1eb0fe78f94633a224eae18ba905e5f5cc93e5e07537330a1846a6cf297d19e9b3b930905d8b0223512626b",
          "sha256": "7bec6346a734f4aad418a7b32e783ff3c0047ce355bab8d50328c223d6d69e42",
          "sha1": "9e1284be8e49a7c7995ab7395bfd93d84a5dd731",
          "md5": "206aa016615219d73d996ce30a62df03"
        }
      ]
    }
  ]
}
