{
  "formatVersion": "1.1",
  "component": {
    "group": "com.elegaiter.sdk",
    "module": "android-user",
    "version": "0.1.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.elegaiter.sdk",
          "module": "android-storage",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "com.elegaiter.sdk",
          "module": "android-network",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "android-user-0.1.5.aar",
          "url": "android-user-0.1.5.aar",
          "size": 13095,
          "sha512": "09540ecd93bf07a8c0306d221dfd992e0cbcea5841117d066d94d6c16aec947b648f441b6627808a2213af9200d7157e07dd4bdfe4b03ebe7f195858f6af9671",
          "sha256": "ae708a95d3e9fd49247ae29acfab2ac8952742021bec581401f72bb5fbad8112",
          "sha1": "e897c3db688e6bcc02b3ebf8ac03748266f2a33b",
          "md5": "2e1de385708d2d63ba827c731c0ba282"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.elegaiter.sdk",
          "module": "common",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "com.elegaiter.sdk",
          "module": "android-core",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-core",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.elegaiter.sdk",
          "module": "android-storage",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "com.elegaiter.sdk",
          "module": "android-network",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "android-user-0.1.5.aar",
          "url": "android-user-0.1.5.aar",
          "size": 13095,
          "sha512": "09540ecd93bf07a8c0306d221dfd992e0cbcea5841117d066d94d6c16aec947b648f441b6627808a2213af9200d7157e07dd4bdfe4b03ebe7f195858f6af9671",
          "sha256": "ae708a95d3e9fd49247ae29acfab2ac8952742021bec581401f72bb5fbad8112",
          "sha1": "e897c3db688e6bcc02b3ebf8ac03748266f2a33b",
          "md5": "2e1de385708d2d63ba827c731c0ba282"
        }
      ]
    }
  ]
}
