{
  "formatVersion": "1.1",
  "component": {
    "group": "com.elegaiter.sdk",
    "module": "android",
    "version": "0.1.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.elegaiter.sdk",
          "module": "common",
          "version": {
            "requires": "0.1.6"
          }
        },
        {
          "group": "com.elegaiter.sdk",
          "module": "android-ble",
          "version": {
            "requires": "0.1.6"
          }
        },
        {
          "group": "com.elegaiter.sdk",
          "module": "android-analysis",
          "version": {
            "requires": "0.1.6"
          }
        },
        {
          "group": "com.elegaiter.sdk",
          "module": "android-storage",
          "version": {
            "requires": "0.1.6"
          }
        },
        {
          "group": "com.elegaiter.sdk",
          "module": "android-network",
          "version": {
            "requires": "0.1.6"
          }
        },
        {
          "group": "com.elegaiter.sdk",
          "module": "android-user",
          "version": {
            "requires": "0.1.6"
          }
        },
        {
          "group": "com.elegaiter.sdk",
          "module": "android-record",
          "version": {
            "requires": "0.1.6"
          }
        },
        {
          "group": "com.elegaiter.sdk",
          "module": "android-core",
          "version": {
            "requires": "0.1.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "android-0.1.6.aar",
          "url": "android-0.1.6.aar",
          "size": 32204,
          "sha512": "0d98bbda9861f98526821a599f187b89cb514b8cdaa06981b64c0c45bea0d69f0dce040decb1b6cac2536463ef74ff1e599d7cb6c295a267c03315d1690e9ad2",
          "sha256": "5a8691516f172bfd8fdcda392aed1cd401b140bb79212e6b2add786e85daf3d4",
          "sha1": "01034a5c817e2fd3ba3d35045bc37709bf226e96",
          "md5": "af23d67c5253c1b6e44e6fc974995fd7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.9.3"
          }
        },
        {
          "group": "com.elegaiter.sdk",
          "module": "common",
          "version": {
            "requires": "0.1.6"
          }
        },
        {
          "group": "com.elegaiter.sdk",
          "module": "android-ble",
          "version": {
            "requires": "0.1.6"
          }
        },
        {
          "group": "com.elegaiter.sdk",
          "module": "android-analysis",
          "version": {
            "requires": "0.1.6"
          }
        },
        {
          "group": "com.elegaiter.sdk",
          "module": "android-storage",
          "version": {
            "requires": "0.1.6"
          }
        },
        {
          "group": "com.elegaiter.sdk",
          "module": "android-network",
          "version": {
            "requires": "0.1.6"
          }
        },
        {
          "group": "com.elegaiter.sdk",
          "module": "android-user",
          "version": {
            "requires": "0.1.6"
          }
        },
        {
          "group": "com.elegaiter.sdk",
          "module": "android-record",
          "version": {
            "requires": "0.1.6"
          }
        },
        {
          "group": "com.elegaiter.sdk",
          "module": "android-core",
          "version": {
            "requires": "0.1.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "android-0.1.6.aar",
          "url": "android-0.1.6.aar",
          "size": 32204,
          "sha512": "0d98bbda9861f98526821a599f187b89cb514b8cdaa06981b64c0c45bea0d69f0dce040decb1b6cac2536463ef74ff1e599d7cb6c295a267c03315d1690e9ad2",
          "sha256": "5a8691516f172bfd8fdcda392aed1cd401b140bb79212e6b2add786e85daf3d4",
          "sha1": "01034a5c817e2fd3ba3d35045bc37709bf226e96",
          "md5": "af23d67c5253c1b6e44e6fc974995fd7"
        }
      ]
    }
  ]
}
