{
  "formatVersion": "1.1",
  "component": {
    "group": "com.elegaiter.sdk",
    "module": "android-user",
    "version": "0.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.elegaiter.sdk",
          "module": "android-storage",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.elegaiter.sdk",
          "module": "android-network",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "android-user-0.2.0.aar",
          "url": "android-user-0.2.0.aar",
          "size": 15651,
          "sha512": "7b066879e34855f94c40c7458ee51df95fe75e87960c450b1a1abbb2d7ae3bbbc5a53970dbfc6a65d3cad14a9a4e2b27c5989f940b2a24c59ded7170a2609edb",
          "sha256": "9a4d83380043a388ea9dad1df8ff27527716b5a369859a2a5700abdd9cf671b5",
          "sha1": "e17792f81b8147a38fbe2bb48805ef4e60409c02",
          "md5": "755653ac2cb17b8a0e6dbd793eb4fdeb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.elegaiter.sdk",
          "module": "common",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.elegaiter.sdk",
          "module": "android-core",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-core",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.elegaiter.sdk",
          "module": "android-storage",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.elegaiter.sdk",
          "module": "android-network",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "android-user-0.2.0.aar",
          "url": "android-user-0.2.0.aar",
          "size": 15651,
          "sha512": "7b066879e34855f94c40c7458ee51df95fe75e87960c450b1a1abbb2d7ae3bbbc5a53970dbfc6a65d3cad14a9a4e2b27c5989f940b2a24c59ded7170a2609edb",
          "sha256": "9a4d83380043a388ea9dad1df8ff27527716b5a369859a2a5700abdd9cf671b5",
          "sha1": "e17792f81b8147a38fbe2bb48805ef4e60409c02",
          "md5": "755653ac2cb17b8a0e6dbd793eb4fdeb"
        }
      ]
    }
  ]
}
