{
  "formatVersion": "1.1",
  "component": {
    "group": "com.elegaiter.sdk",
    "module": "android-analysis",
    "version": "0.1.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.elegaiter.sdk",
          "module": "android-core",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "android-analysis-0.1.5.aar",
          "url": "android-analysis-0.1.5.aar",
          "size": 42242,
          "sha512": "7d8e5c10ab3bae5bcd2c4d49056b2d8ef69acf745f1e7b1901264a7a7fb2b383ec300e9ddc94c513ee5ce12d25eb9e93b5edc485fb4e52086c1baf2db334f5b2",
          "sha256": "df4b2b8a10ea15c74bc8ddd9e3f7989e098e32fb9df46c1d950d8c7897423c6e",
          "sha1": "0b0c9247cdbfed746c29f0f3e977c0ac56cdb649",
          "md5": "ffaf3d18cec0a8da496b4cc25529b342"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.elegaiter.sdk",
          "module": "common",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.elegaiter.sdk",
          "module": "android-core",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "android-analysis-0.1.5.aar",
          "url": "android-analysis-0.1.5.aar",
          "size": 42242,
          "sha512": "7d8e5c10ab3bae5bcd2c4d49056b2d8ef69acf745f1e7b1901264a7a7fb2b383ec300e9ddc94c513ee5ce12d25eb9e93b5edc485fb4e52086c1baf2db334f5b2",
          "sha256": "df4b2b8a10ea15c74bc8ddd9e3f7989e098e32fb9df46c1d950d8c7897423c6e",
          "sha1": "0b0c9247cdbfed746c29f0f3e977c0ac56cdb649",
          "md5": "ffaf3d18cec0a8da496b4cc25529b342"
        }
      ]
    }
  ]
}
