{
  "formatVersion": "1.1",
  "component": {
    "group": "com.elegaiter.sdk",
    "module": "android-ble",
    "version": "0.1.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.elegaiter.sdk",
          "module": "android-core",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "android-ble-0.1.5.aar",
          "url": "android-ble-0.1.5.aar",
          "size": 18393,
          "sha512": "216a3f8d628ef3f6238d46ff944cb3ad78ca494a6df82d8f629cbf74c3b1ddc134b88f94b06a4e5d872b3a2db63e3ae57a4f3fba385a1801a1c4533334156059",
          "sha256": "711839d101e69df6f3da491d2597f92f2c102e6a95b68f1e5a66b8f137500423",
          "sha1": "b5f6fd1b828d02c06e08bfadd068222b63c132a8",
          "md5": "b60bd614f593e455a8a8695a3b589509"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.elegaiter.sdk",
          "module": "common",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "com.elegaiter.sdk",
          "module": "android-core",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "android-ble-0.1.5.aar",
          "url": "android-ble-0.1.5.aar",
          "size": 18393,
          "sha512": "216a3f8d628ef3f6238d46ff944cb3ad78ca494a6df82d8f629cbf74c3b1ddc134b88f94b06a4e5d872b3a2db63e3ae57a4f3fba385a1801a1c4533334156059",
          "sha256": "711839d101e69df6f3da491d2597f92f2c102e6a95b68f1e5a66b8f137500423",
          "sha1": "b5f6fd1b828d02c06e08bfadd068222b63c132a8",
          "md5": "b60bd614f593e455a8a8695a3b589509"
        }
      ]
    }
  ]
}
